apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-lab
  labels:
    app: gitops-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-lab
  template:
    metadata:
      labels:
        app: gitops-lab
    spec:
      containers:
        - name: web
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
